# Generated by Django 5.2.17 on 2026-09-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentallocation',
            name='days_covered',
        ),
        migrations.RemoveField(
            model_name='paymentallocation',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='paymentallocation',
            name='to_date',
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
