# Generated by Django 5.2.17 on 2026-09-14 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], default='PRESENT', max_length=20)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='library.seat')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='students.studentprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'date'), name='one_attendance_per_student_per_day')],
            },
        ),
    ]
