# Generated by Django 5.2.17 on 2026-09-15 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0002_timeslot_seatallocation_end_time_and_more'),
        ('students', '0003_alter_studentprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preferred_students', to='library.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preferred_students', to='library.timeslot'),
        ),
    ]
